targets:
  $default:
    builders:
      reflectable:
        generate_for:
          # Generate the reflectable initializer only for the tests we need
          - test/transactions/create/tx_builder_test.dart

          - test/types/rest/transactions_response_test.dart
          - test/types/tx/std_signature_message_test.dart

          - test/x/bank/types/messages/msg_send_test.dart
          - test/x/staking/types/messages/msg_create_validator_test.dart
          - test/x/staking/types/messages/msg_edit_validator_test.dart
          - test/x/txs/querier_test.dart
        options:
          formatted: true
