targets:
  $default:
    builders:
      reflectable:
        generate_for:
          # Generate the reflectable initializer only for the tests we need
          - test/codec/codec_test.dart

          - test/transactions/create/tx_builder_test.dart
          - test/transactions/send/tx_sender_test.dart

          - test/types/rest/transactions_response_test.dart
          - test/types/tx/std_signature_message_test.dart

          # Bank tests
          - test/x/bank/types/messages/msg_send_test.dart

          # Gov tests
          - test/x/gov/types/content_test.dart
          - test/x/gov/types/messages/msg_submit_proposal_test.dart
          - test/x/gov/types/messages/msg_deposit_test.dart
          - test/x/gov/types/messages/msg_vote_test.dart

          # Staking tests
          - test/x/staking/types/messages/msg_begin_redelegate_test.dart
          - test/x/staking/types/messages/msg_create_validator_test.dart
          - test/x/staking/types/messages/msg_delegate_test.dart
          - test/x/staking/types/messages/msg_edit_validator_test.dart
          - test/x/staking/types/messages/msg_undelegate_test.dart
          - test/x/staking/querier_test.dart

          # Txs tests
          - test/x/txs/querier_test.dart
        options:
          formatted: true
