name: sacco
description: What composes a Borsellino.
version: 0.0.1
author: Riccardo Montagnin <riccardo.montagnin@gmail.com>
homepage: https://github.com/commercionetwork/sacco

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hex: ^0.1.2
  http: ^0.12.0

  # Crypto utils
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  pointycastle: ^1.0.1
  bip_bech32: ^0.1.3

  # Serialization
  json_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: