name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.40.0+1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ^0.39.10
  asn1lib: ^0.6.4
  bip32: ^1.0.7
  bip39: ^1.0.3
  bip_bech32: ^0.1.3
  equatable: ^1.2.0
  fixnum: ^1.0.0
  grpc: ^2.8.0
  hex: ^0.1.2
  http: ^0.12.1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  meta: ^1.2.4
  pointycastle: ^1.0.2
  protobuf: ^1.1.0

dev_dependencies:
  build_runner: ^1.10.1
  convert: ^3.0.0
  mockito: ^4.1.1
  mock_web_server: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.15.5
  test_coverage: ^0.5.0
