name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.39.2
homepage: https://github.com/alan-sdk/alan.dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ^0.39.10
  asn1lib: ^0.6.4
  bip32: ^1.0.5
  bip39: ^1.0.3
  bip_bech32: ^0.1.3
  bitcoin_flutter: ^2.0.1
  equatable: ^1.2.0
  hex: ^0.1.2
  http: ^0.12.1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  meta: ^1.1.8
  pointycastle: ^1.0.2
  reflectable: ^2.2.5

dev_dependencies:
  build_runner: ^1.10.0
  mockito: ^4.1.1
  mock_web_server: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.7
  test_coverage: ^0.4.2
