name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.0.14
author: Riccardo Montagnin <riccardo.montagnin@gmail.com>
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.39.2+1
  meta:
  hex:
  http:
  equatable:
  json_annotation:
  json_serializable:

  # Crypto utils
  asn1lib:
  bip32:
  bip39:
  bitcoin_flutter:
  pointycastle:
  bip_bech32:

dev_dependencies:
  test:
  build_runner:
