name: alan
description: Pure Dart library allowing you to deal with Cosmos-based wallets and transactions.
version: 0.0.1
author: Riccardo Montagnin <riccardo.montagnin@gmail.com>
homepage: https://github.com/alan-sdk/alan.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer:
  asn1lib:
  bip32:
  bip39:
  bip_bech32:
  bitcoin_flutter:
  equatable:
  hex:
  http:
  json_annotation:
  json_serializable:
  meta:
  pointycastle:

dev_dependencies:
  build_runner:
  mockito:
  mock_web_server:
  test:
