name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.0.14
author: Riccardo Montagnin <riccardo.montagnin@gmail.com>
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.39.2+1
  meta: ^1.1.8
  hex: ^0.1.2
  http: ^0.12.0+4
  equatable: ^1.0.2
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5

  # Crypto utils
  asn1lib: ^0.5.15
  bip32: ^1.0.5
  bip39: ^1.0.3
  bitcoin_flutter: ^1.1.0
  pointycastle: ^1.0.2
  bip_bech32: ^0.1.3

dev_dependencies:
  test: ^1.11.0
  build_runner: ^1.7.3
