name: scripts
description: Test scripts
version: 0.1.0
homepage: https://github.com/alan-sdk/alan.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  test_coverage: ^0.4.2

dev_dependencies:
  test: ^1.14.7
