// Mocks generated by Mockito 5.0.3 from annotations
// in alan/test/transactions/signer/tx_signer_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:alan/queries/query_helper.dart' as _i4;
import 'package:alan/x/auth/account.dart' as _i2;
import 'package:alan/x/auth/querier.dart' as _i5;
import 'package:alan/x/node/node_info_response.dart' as _i3;
import 'package:alan/x/node/querier.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeAccountI extends _i1.Fake implements _i2.AccountI {}

class _FakeNodeInfo extends _i1.Fake implements _i3.NodeInfo {}

class _FakeRequestResult<T> extends _i1.Fake implements _i4.RequestResult<T> {}

/// A class which mocks [AuthQuerier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthQuerier extends _i1.Mock implements _i5.AuthQuerier {
  MockAuthQuerier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AccountI?> getAccountData(String? address) =>
      (super.noSuchMethod(Invocation.method(#getAccountData, [address]),
              returnValue: Future.value(_FakeAccountI()))
          as _i6.Future<_i2.AccountI?>);
}

/// A class which mocks [NodeQuerier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeQuerier extends _i1.Mock implements _i7.NodeQuerier {
  MockNodeQuerier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.NodeInfo> getNodeInfo(String? lcdEndpoint) =>
      (super.noSuchMethod(Invocation.method(#getNodeInfo, [lcdEndpoint]),
              returnValue: Future.value(_FakeNodeInfo()))
          as _i6.Future<_i3.NodeInfo>);
  @override
  _i6.Future<_i4.RequestResult<Map<String, dynamic>>> queryChain(String? url) =>
      (super.noSuchMethod(Invocation.method(#queryChain, [url]),
              returnValue:
                  Future.value(_FakeRequestResult<Map<String, dynamic>>()))
          as _i6.Future<_i4.RequestResult<Map<String, dynamic>>>);
}
