name: Release

# Release workflow builds and published a new version to https://pub.dev.
# This workflow is run on new tags.
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main