name: Test

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup 🔨
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.0'
          channel: 'stable'

      - name: Get dependencies 📥
        run: pub get

      - name: Analyze 🔍
        run: make lint

  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup 🔨
        uses: cedx/setup-dart@v2

      - name: Get dependencies 📥
        run: pub get

      - name: Test 🔧
        run: |
          pub global activate coverage

          dart scripts/collect_tests.dart
          pub run test --coverage=coverage test/.test_coverage.dart
          pub global run coverage:format_coverage --packages=.packages -i coverage/test/.test_coverage.dart.vm.json --lcov > coverage/lcov.info

      - name: Clean coverage 🧹
        run: |
          pub global activate remove_from_coverage

          # Exclude all g.dart files
          pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$'

          # Exclude the test folder
          pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '/test/'

      - name: Upload coverage 📤
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          fail_ci_if_error: true
