name:  Test

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:

  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup 🔨
        uses: cedx/setup-dart@v2

      - name: Test 🔧
        run: |
          pub get
          pub run build_runner build --delete-conflicting-outputs
          pub run test test
